name: Build Unsigned iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest # 必须用 macOS 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.84.1

      - name: Add iOS targets to Rust
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Tauri iOS init
        run: | 
          npm install -g bun
          bun install
          bun tauri ios init
          bun tauri icon

      - name: Setup Fake Xcodebuild Wrapper
        run: |
          mkdir -p /tmp/tauri_wrapper
          REPO_DIR="$PWD"
          cat << EOF > /tmp/tauri_wrapper/xcodebuild
          #!/bin/bash
          PROJ_FILE="$REPO_DIR/src-tauri/gen/apple/ren-rs.xcodeproj/project.pbxproj"
          if [ -f "\$PROJ_FILE" ]; then
            sed -i '' 's/DEVELOPMENT_TEAM = ".*"/DEVELOPMENT_TEAM = ""/g' "\$PROJ_FILE"
            sed -i '' '/CODE_SIGN_IDENTITY/d' "\$PROJ_FILE"
            sed -i '' '/DEVELOPMENT_TEAM = "";/a\\nCODE_SIGN_STYLE = Manual;\\n' "\$PROJ_FILE"
          fi
          cat \$PROJ_FILE
          /usr/bin/xcodebuild "\$@"
          EOF
          chmod +x /tmp/tauri_wrapper/xcodebuild
      - name: Build Unsigned Archive via Tauri
        env:
          APPLE_DEVELOPMENT_TEAM: "woainimiao"
          # DEVELOPMENT_TEAM: ""
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_ALLOWED: "NO"
          CODE_SIGNING_REQUIRED: "NO"
          PROVISIONING_PROFILE_SPECIFIER: ""
        run: |
          export PATH="/tmp/tauri_wrapper:$PATH"
          bun tauri ios build

      - name: Package Unsigned .ipa
        run: |
          ARCHIVE_PATH=$(find src-tauri -name "*.xcarchive" | head -n 1)
          echo "Found archive at: $ARCHIVE_PATH"
          mkdir -p Payload
          cp -R "$ARCHIVE_PATH/Products/Applications/"*.app Payload/
          zip -r MyApp.unsigned.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: MyApp.unsigned.ipa
